export const BUSINESS_CATEGORIES = [
  "Mobiles & Accessories",
  "Computers & Peripherals",
  "Consumer Electronics",
  "Home Appliances",
  "Hardware & Tools",
  "Electricals & Lighting",
  "Building Materials",
  "Paints & Sanitary",
  "Automobile Parts & Accessories",
  "Two-Wheeler Spares",
  "Grocery & General Store",
  "FMCG & Packaged Foods",
  "Fruits & Vegetables",
  "Dairy & Frozen Foods",
  "Bakery & Confectionery",
  "Garments & Fashion",
  "Footwear",
  "Jewelry & Watches",
  "Beauty & Personal Care",
  "Pharmacy & Wellness",
  "Furniture & Home Decor",
  "Kitchenware & Plastic Goods",
  "Stationery & Books",
  "Toys & Gifts",
  "Sports & Fitness",
  "Pet Supplies",
  "Agriculture Inputs",
  "Industrial Supplies",
  "Services",
  "Other",
] as const;
